const Constants = {
	SUBREDDIT_SELECTED: 'SUBREDDIT_SELECTED',
	SUBREDDIT_REFRESHED: 'SUBREDDIT_REFRESHED',

	POSTS_REQUESTING: 'POSTS_REQUESTING',
	POSTS_RECEIVED: 'POSTS_RECEIVED',

	COMMENTS_REQUESTING: 'COMMENTS_REQUESTING',
	COMMENTS_RECEIVED: 'COMMENTS_RECEIVED'
};

export default Constants;
